
flowchart

broadcaster
hb[%hb]
mx[%mx]
xh[%xh]
tg[%tg]
kp[%kp]
mj[%mj]
cq[%cq]
mt[%mt]
rm[%rm]
hx[%hx]
xv[%xv]
xx[%xx]
pt[%pt]
vx[%vx]
xb[%xb]
xk[%xk]
lv[%lv]
kn[%kn]
sj[%sj]
jm[%jm]
rr[%rr]
tz[%tz]
gg[%gg]
qc[%qc]
kb[%kb]
vp[%vp]
fb[%fb]
rd[%rd]
qn[%qn]
xr[%xr]
tp[%tp]
cp[%cp]
qq[%qq]
xq[%xq]
gx[%gx]
bq[%bq]
cv[%cv]
zk[%zk]
vh[%vh]
qv[%qv]
lz[%lz]
nj[%nj]
gr[%gr]
kh[%kh]
vm[%vm]
rz[%rz]
rv[%rv]
vj[%vj]

jj[&jj]
xz[&xz]
rk[&rk]
gh[&gh]
cd[&cd]
bz[&bz]
zf[&zf]
qx[&qx]
gf[&gf]

broadcaster-->fb
broadcaster-->xk
broadcaster-->gr
broadcaster-->vj
hb-->mj
mx-->mt
mx-->xz
xh-->qc
tg-->cq
kp-->xz
kp-->nj
mj-->jj
mj-->lv
cq-->jm
mt-->sj
mt-->xz
jj-->hb
jj-->lz
jj-->rk
jj-->xv
jj-->vj
jj-->vh
jj-->lv
rm-->bz
rm-->xq
hx-->bz
xv-->lz
xx-->kp
xx-->xz
pt-->vx
xz-->bq
xz-->gr
xz-->sj
xz-->rv
xz-->zf
vx-->gf
vx-->cv
xb-->xz
xb-->bq
xk-->gf
xk-->rd
lv-->zk
rk-->gh
kn-->gf
kn-->tz
sj-->vp
jm-->vm
jm-->bz
rr-->rv
rr-->xz
tz-->rz
gg-->kn
cd-->gh
qc-->kh
qc-->bz
kb-->gf
vp-->xz
vp-->xx
fb-->bz
fb-->tg
rd-->cp
qn-->vh
qn-->jj
xr-->jj
tp-->rm
tp-->bz
cp-->gg
bz-->qx
bz-->cq
bz-->xh
bz-->fb
bz-->tg
qq-->pt
qq-->gf
xq-->bz
xq-->hx
gx-->jj
gx-->qv
bq-->rr
cv-->gf
cv-->kb
zk-->jj
zk-->xv
zf-->gh
qx-->gh
vh-->gx
qv-->xr
qv-->jj
lz-->qn
nj-->xz
gr-->xz
gr-->xb
kh-->tp
kh-->bz
vm-->bz
vm-->xh
rz-->qq
rz-->gf
gf-->tz
gf-->cd
gf-->rd
gf-->xk
gf-->pt
gf-->cp
gf-->gg
rv-->mx
vj-->hb
vj-->jj
gh-->rx

classDef Conjuction fill:#00DD00,stroke:#006600,stroke-width:1px,color:#006600
class jj Conjuction
class xz Conjuction
class rk Conjuction
class gh Conjuction
class cd Conjuction
class bz Conjuction
class zf Conjuction
class qx Conjuction
class gf Conjuction
